Show realm in credential promt
datalad/datalad-next pull request #396
Opened 2023-06-01 07:54 UTC by christian-monch

This PR inserts information about the protection realm into the credential prompt for 401-error handling. This allows a user to enter a credential matching the protection realm.

2023-06-02 12:43 UTC, mih requested changes
There is no demo of the new vs old prompt in the PR or a commit message (would insist on the latter and appreciate the former). Without that we would not know how it is supposed to look beyond the str-match test included.

My concern is a lot of duplication between `url` and `realm` -- but I might just not remember what they actually are.

2023-06-05 09:11 UTC, christian-monch commented
> Thanks for the PR.
> 
> There is no demo of the new vs old prompt in the PR or a commit message (would insist on the latter and appreciate the former). Without that we would not know how it is supposed to look beyond the str-match test included.
> 
> My concern is a lot of duplication between `url` and `realm` -- but I might just not remember what they actually are.

I amended the PR description and the commit. I added a number of examples that show that `url` and `realm` are often different and point to the definition (RFC 2617) to highlight that there is no defined relation between a `URL-path` and a realm, other than the `WWW-Authenticate`-header.

2023-06-05 10:56 UTC, mih commented
Thanks. I am aware how this works in general. What I was talking about is how a prompt actually looks (i.e. what a user sees). I see the template change in the diff, but it is unclear what the content of the variable `realm` actually is at that point. Putting the real output comparison in the description helps with that. Otherwise, I have to try to run it, as soon as I get to it.

2023-06-05 14:17 UTC, christian-monch commented
> Thanks. I am aware how this works in general.

Sorry, didn't mean to sound like a condescending prick. That wasn't my intention.

> What I was talking about is how a prompt actually looks...

I see now, what you mean. Yes, necessarily the scheme- and location-part would be identical. I still think it would be beneficial for the user to output the realm. I could change it to something like

```
Credential needed for realm ``https://docs.inm7.de/INM-7 Documentation´´ (which controls access to resource ``/learning´´)
```
WDYT?

2023-06-06 07:51 UTC, christian-monch commented
> What about [...]

I like it. Changed to your proposal in 39305eec52f20fa833de830b6a703e7b5d4fd9ab. Credential prompt is now:

```
Credential needed for accessing https://docs.inm7.de/learning (authentication realm 'INM-7 Documentation')
``` 

in contrast to the following from `main`-branch:

```
Credential needed for access to https://docs.inm7.de/learning
```

2023-06-06 09:34 UTC, merged